# Generated by Django 5.0.7 on 2026-07-13

from django.db import migrations


def create_daily_digest_task(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='8',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    PeriodicTask.objects.get_or_create(
        crontab=schedule,
        name='Daily Digest: Pending Tasks Approval',
        task='apps.notifications.tasks.send_daily_digest',
    )


def remove_daily_digest_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(name='Daily Digest: Pending Tasks Approval').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.RunPython(create_daily_digest_task, remove_daily_digest_task),
    ]
